# Generated by Django 2.0 on 2018-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_project3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=200, unique=True)),
                ('abbreviation', models.CharField(help_text='Abbreviation', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Abr',
        ),
        migrations.DeleteModel(
            name='Project3',
        ),
    ]
