# Generated by Django 2.0 on 2018-03-30 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20180328_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_name',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='short_name',
            name='shortName',
            field=models.CharField(default=django.utils.timezone.now, help_text='shortName', max_length=200),
            preserve_default=False,
        ),
    ]
